name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: matura_pro_ai

      - name: Analyze code
        run: flutter analyze
        working-directory: matura_pro_ai

      - name: Run tests
        run: flutter test
        working-directory: matura_pro_ai
